variables:
  #variavle configured on GITLAB
  ACCESS_KEY: $ACCESS_KEY
  SECRET_KEY: $SECRET_KEY
  VERSION: $VERSION
  REGION: $REGION
  JAR_NAME: "infnet-devops-project-0.0.1-SNAPSHOT.jar"

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - sonar
  - deploy
  - notification

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
   # - gradle clean
   # - gradle build
    - echo "AWS CONNECT"
    - ls
    - sh ./configure_aws.sh $ACCESS_KEY $SECRET_KEY $REGION

  artifacts:
    paths:
      - build/libs/

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - gradle test
    - echo "Code coverage is 90%"
  artifacts:
    paths:
      - build/libs
  dependencies:
    - build-job

#Simulating code quality
sonarlint-test-job:   # This job also runs in the test stage.
  stage: sonar    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting code... This will take about 10 seconds."
    - echo "No lint issues found."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application to S3"
    - echo "Verifing if the File Exist
    - ls build/libs
    #deploy to artfactory nexus, jfrog
    - echo "Application successfully deployed."
  dependencies:
    - sonarlint-test-job

sucess-notification:
  stage: notification
  when: on_success
  script:
    - echo "Sucess"
    #send message to e-mail, slack e etc

failure-notification:
  stage: notification
  when: on_failure
  script:
    - echo "error"
  #send message to e-mail, slack e etc
