version: '3'
services:
  api:
    image: infnet-devops-project_api
    command: ["java", "-jar", "infnet-devops-project-0.0.1-SNAPSHOT.jar"]
    environment:
      AMBIENTE: development
    ports:
      - "8088:8080"

