
###

DELETE http://localhost:8088/user/12


###

GET http://localhost:8088/user/12

###
POST localhost:8088/user
Content-Type: application/json

{
  "id": 1,
  "name": "Bill12",
  "lastName": "Hicks",
  "zipCode": "300010-666",
  "number": 306
}

